sidebar:
  menu:
    post: '[博客](/)'
    wiki: '[项目](/wiki/)'
    more: '[关于本人](/about/)'

article:
  # 分类颜色
  category_color:
    'Essay': '#DA0F47'
    'Experiment': '#03a9f4'
    'Log': '#ff9800'
    'Notebook': '#ffa000'
  share: [wechat, weibo, email, link]
  related_posts:
    enable: false
    auto_cover: false



# 使用MathJax渲染数学公式
# 需在Markdown文件开头加入mathjax: true（不加也可以渲染）
# 需要使用Pandoc: npm uninstall hexo-renderer-marked --save & npm install hexo-renderer-pandoc --save 
# 若使用pandoc,footer里的markdown无法正确渲染。但是不使用pandoc，有大量公式的笔记无法正常渲染，hexo g会报错
# pandoc比marked要慢一百倍
# 需要更改 node_modules/hexo-renderer-mathjax/mathjax.html中的脚本路径为https,不然无法渲染
# Katex用不了


#底部图标
footer:
  social:
    Github:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/bit704
    CSDN:
      icon: '<img src="https://tva2.sinaimg.cn/large/0077Un8Egy1h5erqs36soj306y06yt95.jpg"/>'
      url: https://blog.csdn.net/CN_BIT
    Star:
      icon: '<img src="https://tvax3.sinaimg.cn/thumbnail/0077Un8Egy1h5froky2bcj306y06yaaa.jpg"/>'
      url: https://github.com/bit704/bit704.github.io
  license: '[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)'
  more: '健康，快乐！'